name: New Retailer
description: Add support for a new retailer.
title: "New Retailer: VENDOR_NAME"
labels: ["new retailer"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - khengyun
body:
  - type: input
    id: vendorDisplayName
    attributes:
      label: Vendor Display Name
      description: The name of the vendor to be displayed on the Changelog page.
      placeholder: ex. Walmart
    validations:
      required: false
  - type: input
    id: vendorLink
    attributes:
      label: Link to Vendor's Home Page
      description: This will be used to link to the vendor's page from the Changelog page.
      placeholder: ex. https://walmart.com
    validations:
      required: false
