import { useState } from "react";
import Head from "next/head";
import Navbar from "../components/navbar";
import Hero from "../components/hero";
import About from "../components/about";
import Projects from "../components/projects";
import Cert from "../components/cert";
import FindMe from "../components/findMe";
import Footer from "../components/footer";
import Feedback from "../components/feedback";

export default function Home() {
    const [isFeedbackOpen, setIsFeedbackOpen] = useState(false);
    const [submitSuccess, setSubmitSuccess] = useState(false);

    const handleOpenFeedback = () => {
        setIsFeedbackOpen(true);
    };

    const handleCloseFeedback = () => {
        setIsFeedbackOpen(false);
        setSubmitSuccess(false);
    };


    return (
        <>
            <Head>
                <title>Zane&apos;s Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/heart.png" />
            </Head>
            <div className="primary-background">
                <Navbar handleOpenFeedback={handleOpenFeedback} />
                <Hero />
            </div>
            <div className="secondary-background">
                <About />
            </div>
            <div className="primary-background">
                <Projects />
            </div>
            <div className="secondary-background">
                <Cert />
            </div>

            <div className="primary-background">
                <FindMe />
            </div>
            <Footer
                handleOpenFeedback={handleOpenFeedback}
            />
            <Feedback
                open={isFeedbackOpen}
                handleClose={handleCloseFeedback}
                submitSuccess={submitSuccess}
                setSubmitSuccess={setSubmitSuccess}
            />
        </>
    );
}
